### ISSUE TITLE
golang build without gx

### ISSUE THREAD

**Issue by victorb** [ipfs-inactive/dev-team-enablement#115]
_From @Stebalien on July 27, 2018 19:39_

I'd like to run the tests on https://github.com/libp2p/go-libp2p-examples without gx to avoid confusing new users. Would it be possible to detect the lack of gx support and use go-get in that case?

_Copied from original issue: ipfs/jenkins#119_

**Comment by daviddias** [comment]
Still a thing?

**Comment by momack2** [comment]
Let's just reopen the original one on jenkins?
