### ISSUE TITLE
Move jenkins-the-service issues from ipfs/jenkins and ipfs/jenkins-libs to protocol/infra

### ISSUE THREAD

**Issue by victorb** [ipfs-inactive/dev-team-enablement#119]
In preparation for the move of ipfs/jenkins to protocol/infra, we should clean up issues and make them easy to migrate

**Comment by VictorBjelkholm** [comment]
I've labelled all of the "jenkins-the-service" issues into it's own label, `CI/Service`, which issues can be found here: https://github.com/ipfs/testing/labels/CI%2FService

**Comment by VictorBjelkholm** [comment]
I'm a bit wary of moving them right now though, as that would mean it looses the visibility it has now, being in a open repository with the rest of the issues the Testing WG cares about.
