### ISSUE TITLE
Consider using JClouds for jenkins

### ISSUE THREAD

**Issue by magik6k** [ipfs-inactive/dev-team-enablement#161]
There is a very nice looking jenkins plugin which would allow us to integrate jenkins with cloud providers - https://plugins.jenkins.io/jclouds-jenkins

I'm not sure how well it works, but I'd say it may be worth trying as it may fix a ton of issues we are having with the current setup:

* No more build queues
* Better security
* Out-of-space
* Possibly more cost effective

**Comment by VictorBjelkholm** [comment]
Yeah, that's an excellent idea. Previous plugins I've looked on only supported linux, jclouds seems to at least support any AMIs in EC2, only left to figure out vSphere scaling.

Will take a look and see if we could integrate this quickly.

**Comment by eefahy** [comment]
@VictorBjelkholm if you're currently working on this you should involve @mburns since we are trying to move this service to infra yeah?

**Comment by mburns** [comment]
@magik6k can this be closed in a post-Jenkins world? Or is it worth reviving?
