### ISSUE TITLE
With the new pipeline, all tests have to wait on Mac OS X Workers to install their deps

### ISSUE THREAD

**Issue by daviddias** [ipfs-inactive/dev-team-enablement#163]
<img width="807" alt="image" src="https://user-images.githubusercontent.com/1211152/47719398-f881ab80-dc42-11e8-91b7-70c77f939732.png">

With the new version of the pipeline, literally every single test run has to wait for the resource limited pool of Mac OS X workers to have one worker free to install their deps. I've waited multiple times 30+ mins just to wait for deps to be installed :/

**Comment by diasdavid** [comment]
Worst! Now if one of the runtimes runs out of space (which happens often), all the other runtime tests get stucked waiting for that one

<img width="761" alt="image" src="https://user-images.githubusercontent.com/1211152/47965466-0c188200-e048-11e8-9920-211f912b5b24.png">
