### ISSUE TITLE
Automate the creation of weekly sync notes

### ISSUE THREAD

**Issue by daviddias** [ipfs-inactive/dev-team-enablement#31]
Can we get this -- https://github.com/ipfs/js-ipfs/issues/1179 -- automated?

**Comment by diasdavid** [comment]
Hi @VictorBjelkholm, @travisperson,

Can we get this done soon? I keep having to set a reminder and do it manually every week.

**Comment by travisperson** [comment]
@VictorBjelkholm is this issue covered by the work you did recently to revive the `ipfs-helper` bot?

**Comment by VictorBjelkholm** [comment]
Yeah, I haven't automated the js-ipfs weekly meetings yet, only ipfs-all-hands so far, so let's keep this open.

**Comment by VictorBjelkholm** [comment]
@diasdavid can you give me the values of the following files:

```
SPRINT_HELPER_REPOSITORY decides which repository the issue should be created at
SPRINT_HELPER_CRYPTPAD_TEMPLATE decides which template to use for the cryptpad
SPRINT_HELPER_FACILITATORS_FILE decides which JSON file to grab facilitators from
SPRINT_HELPER_ISSUE_TITLE decides the title of the issue
SPRINT_HELPER_ISSUE_TEMPLATE decides which template to use for creating the issue
```

You can see the example values for the IPFS all-hands here: https://github.com/ipfs/sprint-helper#configuration-environment-variables

**Comment by diasdavid** [comment]
- SPRINT_HELPER_REPOSITORY - https://github.com/ipfs/pm/
- SPRINT_HELPER_CRYPTPAD_TEMPLATE - https://github.com/ipfs/pm/blob/master/templates/JS-IPFS-CORE-WEEKLY.md
- SPRINT_HELPER_FACILITATORS_FILE - I'm always the lead and when I'm unavailable I request someone
- SPRINT_HELPER_ISSUE_TITLE - `ⒿⓈ⚡️ js-ipfs Core Dev Team Weekly <Month> <Day>, <Year>`
- SPRINT_HELPER_ISSUE_TEMPLATE - You can grab the template from https://github.com/ipfs/js-ipfs/issues/1179

**Comment by rogerlzp** [comment]
@VictorBjelkholm do you need more people to make the tests automated?

**Comment by VictorBjelkholm** [comment]
Making clear the reasons why this stopped being developed. Took long time to have everything working, so we temporary moved to Google Docs. When that move happened, bunch of people took liking to using Google Docs, and now we're unsure if we want to move away from it back to HackMD/Cryptpad.

**Comment by VictorBjelkholm** [comment]
Right, changed it to be more general as this is a issue for many projects, not just JS Core Dev Weekly Syncs.

Once we have a "miscellaneous" env for services like this in the new infrastructure ([issue in protocol/infra](https://github.com/protocol/infra/issues/291)), we can set this up again. Code should be ready for it (https://github.com/ipfs/sprint-helper) as long as the env vars are setup.

**Comment by daviddias** [comment]
Tracked https://github.com/ipfs/team-mgmt/issues/730 and led by @pkafei
