### ISSUE TITLE
Interop tests

### ISSUE THREAD

**Issue by achingbrain** [ipfs-inactive/dev-team-enablement#49]
We have [some tests](https://github.com/ipfs/interop) designed to guarantee interoperability between the js and go implementations (also [these ones](https://github.com/ipfs/interface-ipfs-core) to a degree although I don't believe it's their primary purpose).

Are they run as part of CI or the release process anywhere? They should really prevent releases if they fail.

**Comment by travisperson** [comment]
@VictorBjelkholm might be able to answer this.
