### ISSUE TITLE
Jenkins runs all code projects CI

### ISSUE THREAD

**Issue by victorb** [ipfs-inactive/dev-team-enablement#88]
_From @VictorBjelkholm on October 6, 2017 8:36_

Projects with tests and code that are in the main organizations (ipfs, libp2p, ipld, multiformats, ipfs-shipyard) should all be using Jenkins for their CI needs. This issue is for tracking the progress.

_Copied from original issue: ipfs/jenkins#67_

**Comment by VictorBjelkholm** [comment]
All JavaScript projects in Multiformats now run on Jenkins! Just a few orgs left to verify 👍
